name = "tracker-app"
compatibility_date = "2024-10-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
DEFAULT_TZ = "UTC"
ALLOWED_ORIGINS = ""

[[d1_databases]]
binding = "DB"
database_name = "tracker-db"
database_id = "dcf4bcd4-da6b-4a04-b3bb-c0171099e337"
